"""Extend emotional_events with flexible schema

Revision ID: 44c7d50f81ed
Revises: 4fa375244ef3
Create Date: 2025-08-15 00:30:16.038859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44c7d50f81ed'
down_revision: Union[str, Sequence[str], None] = '4fa375244ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotional_events', sa.Column('session_id', sa.String(), nullable=True))
    op.add_column('emotional_events', sa.Column('source', sa.String(), nullable=True))
    op.add_column('emotional_events', sa.Column('emotion_label', sa.String(), nullable=True))
    op.add_column('emotional_events', sa.Column('valence', sa.Float(), nullable=True))
    op.add_column('emotional_events', sa.Column('arousal', sa.Float(), nullable=True))
    op.add_column('emotional_events', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('emotional_events', sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('emotional_events', sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('emotional_events', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('emotional_events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_emotional_events_session_id'), 'emotional_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_emotional_events_user_id'), 'emotional_events', ['user_id'], unique=False)
    op.drop_column('emotional_events', 'emotion')
    op.drop_column('emotional_events', 'intensity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotional_events', sa.Column('intensity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('emotional_events', sa.Column('emotion', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_emotional_events_user_id'), table_name='emotional_events')
    op.drop_index(op.f('ix_emotional_events_session_id'), table_name='emotional_events')
    op.alter_column('emotional_events', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('emotional_events', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('emotional_events', 'ingested_at')
    op.drop_column('emotional_events', 'raw_payload')
    op.drop_column('emotional_events', 'confidence')
    op.drop_column('emotional_events', 'arousal')
    op.drop_column('emotional_events', 'valence')
    op.drop_column('emotional_events', 'emotion_label')
    op.drop_column('emotional_events', 'source')
    op.drop_column('emotional_events', 'session_id')
    # ### end Alembic commands ###
